add docker ignore
Janin-Michel-Mathias/api-projet pull request #2
Opened 2024-04-23 20:51 UTC by vanande

2024-04-23 20:56 UTC, vanande commented
Viens me review @Janin-Michel-Mathias

2024-04-24 06:28 UTC, Janin-Michel-Mathias requested changes
Même si on ne s'en sert pas en prod, quel est l'intérêt de garder les dev dépendances dans le docker puisque tu ne vas pas dev dedans ?

2024-04-25 19:59 UTC, vanande commented
@Janin-Michel-Mathias viens me review, t'en penses quoi mtn

2024-04-25 20:02 UTC, vanande commented
New : 
- Add postgres image
- Connect to the postgre image

Removed : 
- Dockerize the app

2024-05-10 13:36 UTC, closed without merging